sudo: false

language: node_js

node_js:
  - 10.16.2

install:
  - npm install -g firebase-tools

script:
  - npm install
  - firebase-ci createConfig
  - npm run build

after_success:
  - npm i -g firebase-ci # install firebase-ci
  - firebase-ci createConfig
  - firebase-ci deploy # deploy to firebase-hosting
