language: node_js
node_js: lts/*
install: true
script: echo $REACT_APP_PROJECT_ID
deploy:
  provider: firebase
  token:
  secure: "ZuEnNNO+nOqUdfBM/8yDeoMsVPfX7zglPyXy8s2kzka/Csia8FzIy6S0BA5ym4CxhMh4Pk9PIYFxCNi/BspC7vkgyrxwRMbmB6l1vxCISXK3z8zrIC03glARH/BJgoafXkdA03aFbX8OJRMMPWo1sd+xpjpeqtpMu1I5OD8ocBHnN0J3qS9+eO7EuhoH3KW04iITqiyxK95Ksl4l2pLUNEeaZ39ZjRt1ASgz9HU8jgt0h4kgsgfIq4+sDYaz13Uk/NWWNztUtaYxF339XQ4+q5sZuKx5gKh2zqYC0AVwJmPexUACteYWmkx/HO//HwTH3JNHX59b0hlfXPCRAn7GmJYgMeLPEeyXFUg6iMoMkGWey3Y3QDvJvnG1FxkjHCTehVtEXsh7zGtIXAchOsOedOEByO83IZ/NBNIypZ44KDp9qr28gIzQl8G6nOdzRnzaXSNQ0VhOgAScdnLfT+9GNTZMdR3fqj+gps+hMcWC1U1mrZQ+2U1P/VKdrozIR5wRqWeec5kjFdIrTkhGY8evc2VCfeEPhoZmMA28vSVEZh0POQ9hz7MLo8cNSr2BOt33wFPnkN7KBGvVhAViYv6RAdd3VqbnJpe9iuMocIKHJw/mtJlbfO+zGICgq31ETFvml32P+zCeeCDwCMXFwQ1BkcvbPhbXQYFVhePDQRlLPiQ="  on:
    branch: develop
