language: node_js
node_js: lts/*
install: true
script: echo $REACT_APP_DATABASE_URL
deploy:
  provider: firebase
  token:
    secure: TnniTfnwdpBp2BSV1o7F7b2asdhGd4k54/I6dGtpWTmBhmR2S8/vButcCZVUcwLa2tdFH5dSK2Zb/VuuBLZRFnL4YDAtG3NaF1b+ig8e70FIHmXvzRp3gydDHlQzpFWm2AEHZ6aKWQcLVpfbG4DJF7Ac999ByfhsDJoMze24KYjr6Ch+AH5r4ssq19bkOXs1T2+53E/boKxdYwhvihM3vuGKXOEyP42HQQMh0BYkpGcJjKTOiwsfvhvDGKhYKL9dpK67lCNysn6MdUmZXHvlnQ1KVmlr7cxWFs9ZDTwgLuOXsMnB5xMquB8483IO+H70ghgIRKOI6SVMDwBrbQumggM3LgTzA+xGdQ7iaNFUF4awHMpBSHNXY8ikKIfCdPEcUIWz4PNb+q+oy80l4q1p43XC1Dc4yGIp6A0BsHUSzSUvL6RoGKutOxXXMfMtimP73SJOKRUJiOW2NPcvVouT4GMrPxj/tqEOXWnbprVGVICT78TswSAi6MX/RXEiFpyUsf8dlUDfYFaIlo6upBEhzkSQ6jfg3Nqf99oEC/Z44mIhSzvVEZbswRiC3NYRpJg8P9+TITHMJ1E+P3nHBvHqumzJ4zxQEciqnigRig8Qn1dTtwGThb6zQH2tYXZkDGujAsQjMq6Jh/QuqKgufNwasNR5Ainm1MjTTyodGVTScF0=
  project: $REAC_APP_PROJECT_ID
